# For more information: https://laravel.com/docs/sail
version: '3.8'
services:
    laravel.test:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            target: base
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        container_name: app-crypto-back
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:8000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${REVERB_PORT-8080}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_CONNECTION: 'pgsql'
            DB_HOST: db
            DB_PORT: 5432
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
            - redis
            - mailhog
        networks:
            - cryptocurrencies-backend-network

    db:
        image: postgres:15
        container_name: db-crypto-back
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - cryptocurrencies-backend-network

    redis:
        image: redis:alpine
        container_name: redis-crypto-back
        volumes:
            - ./redis:/data
        ports:
            - "6379:6379"
        networks:
            - cryptocurrencies-backend-network


    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: mailhog-crypto-back
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - cryptocurrencies-backend-network

    adminer:
        image: adminer
        container_name: adminer-crypto-back
        restart: always
        networks:
            - cryptocurrencies-backend-network

volumes:
    db-data:

networks:
    cryptocurrencies-backend-network:
        driver: bridge
