version: "3.8"

services:
  laravel.test:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: dev
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    container_name: app-crypto-back
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:8000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      - '${REVERB_PORT-8080}:8080'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      DB_CONNECTION: 'pgsql'
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
    networks:
      - cryptocurrencies-backend-network

  adminer:
    image: adminer
    container_name: adminer-crypto-back
    restart: unless-stopped
    ports:
      - "1337:8080"
    networks:
      - cryptocurrencies-backend-network
